openapi: 3.1.0
info:
  version: 1.0.0
  title: AquaTrack
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of AquaTrack application for water intake tracking.
tags:
  - name: Water
    description: Operations related to managing water consumption.
  - name: User
    description: Operations related to managing users profiles.
servers:
  # update server url when we go live
  - url: http://localhost:3000
  - url: https://aquatrackerapp.onrender.com
    description: Production server
paths:
  /water:
    post:
      $ref: ../swagger/paths/water/post.yaml
  /water/{id}:
    patch:
      $ref: ../swagger/paths/water/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/water/{id}/delete.yaml
  /water/day:
    get:
      $ref: ../swagger/paths/water/day/get.yaml
  /water/month:
    get:
      $ref: ../swagger/paths/water/month/get.yaml
  /users/total:
    get:
      $ref: ../swagger/paths/users/get/total.yaml
  /users/get-oauth-url:
    get:
      $ref: ../swagger/paths/users/get/get-oauth-url.yaml
  /users/current:
    get:
      $ref: ../swagger/paths/users/get/current.yaml
  /users/update:
    patch:
      $ref: ../swagger/paths/users/patch/update.yaml
  /users/register:
    post:
      $ref: ../swagger/paths/users/post/register.yaml
  /users/login:
    post:
      $ref: ../swagger/paths/users/post/login.yaml
  /users/logout:
    post:
      $ref: ../swagger/paths/users/post/logout.yaml
  /users/refresh:
    post:
      $ref: ../swagger/paths/users/post/refresh.yaml
  /users/confirm-google-auth:
    post:
      $ref: ../swagger/paths/users/post/confirm-google-auth.yaml
  /users/request-reset-email:
    post:
      $ref: ../swagger/paths/users/post/request-reset-email.yaml
  /users/reset-password:
    post:
      $ref: ../swagger/paths/users/post/reset-password.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
